apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: forcenetpols.lab.local
spec:
  group: lab.local
  names:
    kind: ForceNetPol
    listKind: ForceNetPolList
    plural: forcenetpols
    singular: forcenetpol
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ForceNetPol is the Schema for the forcenetpols API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ForceNetPolSpec defines the desired state of ForceNetPol
          type: object
        status:
          description: ForceNetPolStatus defines the observed state of ForceNetPol
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
