kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: networkpolicies-operator
subjects:
- kind: ServiceAccount
  name: networkpolicies-operator
  namespace: network-policies-operator
roleRef:
  kind: ClusterRole
  name: networkpolicies-operator
  apiGroup: rbac.authorization.k8s.io
